Speed up 'docker load images' in harbor job start
Unzip the harbor images tgz file into a tar file in packaging phase,
then docker loading this tar file will be faster than loading the tgz
file. This is to reduce the possibility of canary timeout issue #3735.

Issue: https://github.com/vmware/harbor/issues/3735

diff --git a/packages/docker/packaging b/packages/docker/packaging
--- a/packages/docker/packaging
+++ b/packages/docker/packaging
@@ -6,9 +6,8 @@ DOCKER_VERSION=`ls -r docker/docker-*.tgz | sed 's/docker\/docker-\(.*\)\.tgz/\1
 
 # Extract docker package
 echo "Extracting docker ${DOCKER_VERSION}..."
-tar xzvf ${BOSH_COMPILE_TARGET}/docker/docker-${DOCKER_VERSION}.tgz
-if [[ $? != 0 ]] ; then
-  echo "Failed extracting docker ${DOCKER_VERSION}"
+if ! tar -xzvf ${BOSH_COMPILE_TARGET}/docker/docker-${DOCKER_VERSION}.tgz ; then
+  echo "Failed to extract docker ${DOCKER_VERSION} tarball"
   exit 1
 fi
 
@@ -16,4 +15,3 @@ echo "Copying docker ${DOCKER_VERSION} binaries..."
 mkdir -p ${BOSH_INSTALL_TARGET}/bin
 cp docker/* ${BOSH_INSTALL_TARGET}/bin
 chmod +x ${BOSH_INSTALL_TARGET}/bin/*
-
diff --git a/packages/harbor-app/packaging b/packages/harbor-app/packaging
--- a/packages/harbor-app/packaging
+++ b/packages/harbor-app/packaging
@@ -5,14 +5,15 @@ source /var/vcap/packages/harbor-common/common.sh
 
 #Extract harbor package to the destination folder
 echo "Extracting Harbor ${HARBOR_FULL_VERSION}..."
-tar xzvf ${BOSH_COMPILE_TARGET}/harbor/harbor-offline-installer-*.tgz
-if [[ $? != 0 ]] ; then
-  echo "Failed to extract Harbor ${HARBOR_FULL_VERSION}"
+file=`ls ${BOSH_COMPILE_TARGET}/harbor/harbor-offline-installer-*.tgz`
+if ! tar -xzvf $file --strip 1 -C ${BOSH_INSTALL_TARGET} ; then
+  echo "Failed to extract Harbor ${HARBOR_FULL_VERSION} tarball"
   exit 1
 fi
 
-#Copy the Harbor files to destination folder
-cp -a ${BOSH_COMPILE_TARGET}/harbor/* ${BOSH_INSTALL_TARGET}/
 chmod +x ${BOSH_INSTALL_TARGET}/*.sh
 chmod +x ${BOSH_INSTALL_TARGET}/prepare
 
+#Unzip the harbor images tgz file to a tar file,
+#then docker loading images in 'ctl start' could be faster.
+gunzip ${BOSH_INSTALL_TARGET}/harbor*.tar.gz
