add accurate status check for harbor process via cron tool

diff --git a/jobs/harbor/templates/bin/status_check.erb b/jobs/harbor/templates/bin/status_check.erb
--- a/jobs/harbor/templates/bin/status_check.erb
+++ b/jobs/harbor/templates/bin/status_check.erb
@@ -6,12 +6,23 @@ set -u # report the usage of uninitialized variables
 HARBOR_JOB_DIR=/var/vcap/jobs/harbor
 CFG_FILE=${HARBOR_JOB_DIR}/config/harbor.cfg
 DOCKER_PACKAGE_DIR=${HARBOR_JOB_DIR}/packages/docker
+RUN_DIR=/var/vcap/sys/run/harbor
+PIDFILE=${RUN_DIR}/pid
 
 export PATH=$PATH:${DOCKER_PACKAGE_DIR}/bin
 
+Timestamp=`date '+%Y-%m-%d %H:%M:%S'`
+
+#Exit function with pid file deletion
+myExit() {
+	echo "$Timestamp Harbor status check: [FAILED]"
+	rm -f $PIDFILE
+	exit $1
+}
+
 #Check the status of Harbor containers
 if docker ps --filter "status=restarting" | grep 'vmware'; then
-	exit 1
+	myExit 1
 fi
 
 #Check the API
@@ -24,8 +35,8 @@ if [[ $(grep 'hostname[[:blank:]]*=' ${CFG_FILE}) =~ hostname[[:blank:]]*=[[:bla
 fi
 <% end %>
 
-if [[ -z ${harbor_url} ]]; then
-	exit 2
+if [ -z ${harbor_url} ]; then
+	myExit 2
 fi
 
 protocol=<%= p("ui_url_protocol") %>
@@ -35,14 +46,27 @@ if [ "$protocol" = "https" ]; then
 	curl_command="$curl_command -k"
 fi
 
+set +e
+
+echo "${curl_command} ${protocol}://${harbor_url}/api/systeminfo"
 url=`${curl_command} ${protocol}://${harbor_url}/api/systeminfo | python -c "import sys, json; print json.load(sys.stdin)['registry_url']"`
 if [ $? != 0 ] ; then
-	exit 3
+	myExit 3
 fi
 
 if [ "$harbor_url" != "$url" ]; then
-	exit 4
+	myExit 4
 fi
 
-echo "Harbor status check: [PASSED]"
+#Check docker registry
+password=<%= p("admin_password") %>
+login=$(docker login -u admin -p $password $harbor_url)
+if [ $? != 0 ] ; then
+  echo $login | grep -q "unauthorized"
+  if [ $? != 0 ] ; then
+    myExit 5
+  fi
+fi
+
+echo "$Timestamp Harbor status check: [PASSED]"
 exit 0
