Update harbor.yml for 2.10.0
  Upgrade nfs-common package in boshrelease
  Refactor nfs-common package to reduce version dependency

diff --git a/packages/nfs-common/packaging b/packages/nfs-common/packaging
--- a/packages/nfs-common/packaging
+++ b/packages/nfs-common/packaging
@@ -1,7 +1,10 @@
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
 
-cp ${BOSH_COMPILE_TARGET}/nfs-common/libc6_2.36-0ubuntu4_amd64.deb ${BOSH_INSTALL_TARGET}
-cp ${BOSH_COMPILE_TARGET}/nfs-common/keyutils_1.6.1-2ubuntu3_amd64.deb ${BOSH_INSTALL_TARGET}
-cp ${BOSH_COMPILE_TARGET}/nfs-common/libnfsidmap1_2.6.1-2ubuntu4.1_amd64.deb  ${BOSH_INSTALL_TARGET}
-cp ${BOSH_COMPILE_TARGET}/nfs-common/rpcbind_1.2.6-2build1_amd64.deb  ${BOSH_INSTALL_TARGET}
-cp ${BOSH_COMPILE_TARGET}/nfs-common/libevent-core-2.1-7a_2.1.12-stable-5ubuntu1_amd64.deb  ${BOSH_INSTALL_TARGET}
-cp ${BOSH_COMPILE_TARGET}/nfs-common/nfs-common_2.6.1-2ubuntu4.1_amd64.deb  ${BOSH_INSTALL_TARGET}
+echo "Extracting nfs-common ..."
+if ! tar -xzvf ${BOSH_COMPILE_TARGET}/nfs-common/nfs-common.tgz -C ${BOSH_INSTALL_TARGET} ; then
+  echo "Failed to extract nfs-common tarball"
+  exit 1
+fi
+
+chmod +x ${BOSH_INSTALL_TARGET}/*.sh
